Portfolio Milestone 8
ambrose-kibet/portfolio pull request #12
Opened 2022-12-20 15:09 UTC by ambrose-kibet

## Portfolio milestone 8 : pop-up display 
### in this milestone we : 
- add a modal to index.html
- add modal functionality to index.js

2022-12-20 16:35 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi Team👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Modal window is working properly ✔️ 

## Required Changes:

- [ ] Kindly add the MIT file to your project because the link in your README file is broken 👍 
- [ ] Please consider following best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add modal window" instead of "modal window added" ... etc. 💯 

_Kindly check the comments below_


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 16:35 UTC, ha-manel commented on index.html
> +            <article class="project-card-variant printing" data-name="printing">
- [ ] Kindly remove the projects cards from the HTML and add them dynamically using JavaScript as mentioned in the project requirements 👇 

![image](https://user-images.githubusercontent.com/50721479/208717086-55194c74-d146-4279-a986-021e5e39c1ba.png)

2022-12-20 16:35 UTC, ha-manel commented on index.js
> +                      class="card-header-img"
- [ ] Good job with the design of the modal window 👏 Kindly add a dark overlay behind the modal with a slight blur (for both desktop and mobile view) as shown in the Figma template 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/208717490-d788db8d-204f-4d61-9578-3725d5b1bdec.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/208717526-1462be0b-a8cb-4d7c-8769-c5907d23acef.png)

2022-12-21 09:03 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ ✔️ 

Hi @ambrose-kibet, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

## Optional suggestions

- [OPTIONAL] As mentioned by the previous reviewer kindly add the `MIT` file to your project because the link that you provided in your README file is broken 🙃 
- [OPTIONAL] Also some of your commit messages are in the past tense and not capitalized, the commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Kindly apply this rule in your next commit messages 🙃 😉

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 12:13 UTC, merged