Portfolio: Milestone 2
ambrose-kibet/portfolio pull request #2
Opened 2022-12-01 15:55 UTC by ambrose-kibet

## In this milstone we:
- Add projects section
- Add about me section
- Add skills section

2022-12-01 16:57 UTC, binhussen requested changes
Hi @ambrose-kibet , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Kindly check all of your image URL
- Please check all of your requirements before doing it. like `display` property 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 16:57 UTC, binhussen commented on index.css
> +  justify-content: center;
- Kindly, use `diplay : grid` according to the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)

2022-12-01 16:57 UTC, binhussen commented on index.html
> +          </article>
- Kindly, make technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li` for a semantic reasons. 👍

2022-12-01 16:57 UTC, binhussen commented on index.html
> +              />
- kindly, make sure your image url is typed correctly if the file is in the same directory use`./` not `/`. 👍 👍

2022-12-01 16:57 UTC, binhussen commented on index.css
> +  background-image: url("/assets/card-bg.png");
- kindly, make sure your image URL is typed correctly if the file is in some directory use`./` not `/`. 👍 👍

2022-12-02 04:55 UTC, Tadesse-Alemayehu approved these changes
### Hi @ambrose-kibet 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. 🙏
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 05:14 UTC, merged